<!---------- Sample Guide ---------->
<div class="cont" style="background:#f5f5f5;border-bottom:1px solid #ddd;">
    <div class="inner">
        <h3 class="tit_b">
            # Hard Coding <span class="t_point">M121_B</span>
            <div class="btn_copy_s">
                <a href="#" class="btn_capy_view"><span>View</span></a>
                <a href="#" class="btn_capy_xmp"><span>Copy</span></a>
            </div>
        </h3>      
    <xmp class="xmp">
    
    </xmp>
    </div>
    <!-- //inner -->
    </div>
    <!-- //Title -->
    
    <textarea id="ClipBoard" style="display:none"></textarea>
    <link rel="stylesheet" type="text/css" href="/kr/offering/guide/md_guide.css">
    <script type="text/javascript" src="/kr/offering/guide/md_guide.js"></script>
    <!---------- //Sample Guide ---------->
    
    <!-- M121_B -->
    <div class="cont M121_B bg" data-fn="" data-tit="" data-section="" data-active-tab="">
        <!-- inner -->
        <div class="inner">
            <div class="view_cont">
                <div class="visual_img">
                    <!-- visual_items -->
                    <div class="visual_items">
                        <section class="visual_items_inner">
                            <div class="item_s">
                                <div class="item_s_cont">
                                    <strong>브라이틱스 AI의 실시간 시각화</strong>
                                    <ul>
                                        <li>
                                            <em>5,361</em>
                                            <p>
                                                등록된<br/>
                                                사용자 수
                                            </p>
                                        </li>
                                        <li>
                                            <em>21,108</em>
                                            <p>
                                                브라이틱스 스튜디오<br/>
                                                다운로드 수
                                            </p>
                                        </li>
                                        <li>
                                            <em>61</em>
                                            <p>
                                                등록된<br/>
                                                Use Case 수
                                            </p>
                                        </li>
                                        <li>
                                            <em>1,377,410</em>
                                            <p>
                                                튜토리얼<br/>
                                                조회 수
                                            </p>
                                        </li>
                                        <li>
                                            <em>299,662</em>
                                            <p>
                                                분석모델 튜토리얼<br/>
                                                다운로드 수
                                            </p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </section>
                    </div>
                    <!-- //visual_items -->
                    <!-- img -->
                    <div class="img">
                        <p class="img_p"><img src="http://70.225.30.32:8002/module_src/images/data/aws_banner_bg.png" alt=""></p>
                        <p class="img_m"><img src="http://70.225.30.32:8002/module_src/images/data/aws_banner_bg.png" alt=""></p>
                    </div>
                    <!-- //img -->
                </div>
            </div>
        </div>
        <!-- //inner -->
    </div>
    
    <!-- M121_B -->
    <div class="cont M121_B bg" data-fn="" data-tit="" data-section="" data-active-tab="">
        <div class="inner">
            <div class="view_cont">
    
                <!-- section -->
                <div class="section why">
                    <div class="inner ban">
                        <strong class="tit_m">왜 삼성SDS 브리티 코파일럿 인가?</strong>
                        <div class="logo" style="background-image:url('https://image.samsungsds.com/kr/ai-fabrix/fabrix_why_logo.png?queryString=20240215103829')"></div>
                    </div>
                    <div class="bgimg">
                        <div class="pc_show" style="background-image:url('https://image.samsungsds.com/kr/ai-fabrix/fabrix_why_pc.png?queryString=20240215103829')"></div>
                        <div class="mo_show" style="background-image:url('https://image.samsungsds.com/kr/ai-fabrix/fabrix_why_mo.png?queryString=20240215103829')"></div>
                    </div>
                </div>
                <!-- //section -->
    
                <!-- section -->
                <div class="section simply">
                    <div class="inner ban">
                        <div class="txt">
                            <dl>
                                <dt>Seamless한 사용성</dt>
                                <dd>어느 위치에서나 (메일, 메신저, 미팅, 드라이브) 자유롭게 생성형 AI 활용!</dd>
                                <dt>명확한 커뮤니케이션</dt>
                                <dd>정확한 음성 인식률을 바탕으로 실시간 자막부터 회의 요약까지 완벽 지원</dd>
                                <dt>생성형 AI 보안 관리</dt>
                                <dd>키워드 필터링 등, 생성형 AI를 안전하게 사용하는 방법</dd>
                            </dl>
                        </div>
                        <div class="img">
                            <div class="pc_show" style="background-image:url('https://image.samsungsds.com/kr/ai-fabrix/fabrix_simply_img.png?queryString=20240215103829')"></div>
                            <div class="mo_show" style="background-image:url('https://image.samsungsds.com/kr/ai-fabrix/fabrix_simply_img.png?queryString=20240215103829')"></div>
                        </div>
                        <div class="slogan">
                            협업 솔루션 Brity Works가 생성형 AI를 만나 <span>Brity Copilot</span>으로 더 강력하게,<br>
                            기업의 <span>일하는 방식의 혁신</span>을 가져옵니다.
                        </div>
                    </div>
                    <div class="bgimg">
                        <div class="pc_show" style="background-image:url('https://image.samsungsds.com/kr/ai-fabrix/fabrix_simply_pc.png?queryString=20240215103829')"></div>
                        <div class="mo_show" style="background-image:url('https://image.samsungsds.com/kr/ai-fabrix/fabrix_simply_mo.png?queryString=20240215103829')"></div>
                    </div>
                </div>
                <!-- //section -->
        
            </div>
        </div>
    </div>
    <!-- //M121_B -->
    
