<!-- M121_B -->
<div id="why" class="cont M121_B" data-tit="왜 브리티 코파일럿인가?" data-section="" data-active-tab="" data-fn="">
    <!-- inner -->
    <div class="inner">
		<div class="view_cont">
  <!-- section -->
  <div class="section why">
    <div class="inner ban">
      <strong class="tit_m">왜 삼성SDS <br class="mo_show">브리티 코파일럿 인가?</strong>
      <div class="logo" style="background-image:url('http://70.225.30.31:8002/kr/copilot/copilot_why_logo.svg?queryString=20240222094706')"></div>
    </div>
    <div class="bgimg">
      <div class="pc_show" style="background-image:url('http://70.225.30.31:8002/kr/copilot/copilot_why_bg_pc.png?queryString=20240222094706')"></div>
      <div class="mo_show" style="background-image:url('http://70.225.30.31:8002/kr/copilot/copilot_why_bg_mo.png?queryString=20240222094706')"></div>
    </div>
  </div>
  <!-- //section -->

  <!-- section -->
  <div class="section simply">
    <div class="inner ban">
      <div class="txt">
        <dl>
          <dt>Seamless한 사용성</dt>
          <dd>어느 위치에서나 (메일, 메신저, 미팅, 드라이브) 자유롭게 생성형 AI 활용!</dd>
          <dt>명확한 커뮤니케이션</dt>
          <dd>정확한 음성 인식률을 바탕으로 실시간 자막부터 회의 요약까지 완벽 지원</dd>
          <dt>생성형 AI 보안 관리</dt>
          <dd>키워드 필터링 등, 생성형 AI를 안전하게 사용하는 방법</dd>
        </dl>
      </div>
      <div class="img">
        <div class="pc_show" style="background-image:url('http://70.225.30.31:8002/kr/copilot/copilot_simply_img_pc.png?queryString=20240222094706')"></div>
        <div class="mo_show" style="background-image:url('http://70.225.30.31:8002/kr/copilot/copilot_simply_img_mo.png?queryString=20240222094706')"></div>
      </div>
      <div class="slogan">
        협업 솔루션 Brity Works가 생성형 AI를 만나 <span>Brity Copilot</span>으로 더 강력해져,<br class="pc_show">
        기업의 <span>일하는 방식의 혁신</span>을 가져옵니다.
      </div>
    </div>
    <div class="bgimg">
      <div class="pc_show" style="background-image:url('http://70.225.30.31:8002/kr/copilot/copilot_simply_bg_pc.png?queryString=20240222094706')"></div>
      <div class="mo_show" style="background-image:url('http://70.225.30.31:8002/kr/copilot/copilot_simply_bg_mo.png?queryString=20240222094706')"></div>
    </div>
  </div>
  <!-- //section -->
</div>

    </div>
    <!-- //inner -->
</div>
<!-- //M121_B -->
